[functions]
  external_node_modules = ["express", "express-validator"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/movies/*"
  status = 200
  to = "/.netlify/functions/movies/:splat"
